import { createServerClient } from './lib/supabase-server.js'
console.log('NEXT_PUBLIC_SUPABASE_URL=', process.env.get('NEXT_PUBLIC_SUPABASE_URL'))
console.log('SUPABASE_URL=', process.env.get('SUPABASE_URL'))
console.log('NEXT_PUBLIC_SUPABASE_ANON_KEY=', process.env.get('NEXT_PUBLIC_SUPABASE_ANON_KEY'))
console.log('SUPABASE_SERVICE_ROLE_KEY=', process.env.get('SUPABASE_SERVICE_ROLE_KEY'))
console.log('NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY=', process.env.get('NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY'))
const client = createServerClient()
const { data, error } = await client.from('concepts').select('*').limit(1)
console.log('select error', error)
console.log('select data', data)
